### ISSUE TITLE
Cannot verify Dash blockchain messages

### ISSUE THREAD

**Issue by abdrasulov** [ConsenSys/mikuli#6]
Hello @bkolad,

I'd like to verify Dash Blockchain messages using mikuli. When I try to decode its public key, the lib throws me an error. The reason is that public key that I'm trying to decode is the byte array with a length of 48, whereas mikuli expects it to be 192. Is there any way to decode it?

**Comment by bkolad** [comment]
@abdrasulov  mikuli and Dash are using different cryptographic schema and are incompatible.

**Comment by bkolad** [comment]
issue not relevant to mikuli.
